export const ADMIN_LOGIN_SUCCESS='ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_ERROR='ADMIN_LOGIN_ERROR'
export const GET_ADMIN_MESSAGES_SUCCESS='GET_ADMIN_MESSAGES_SUCCESS'
export const GET_ADMIN_MESSAGES_ERROR='GET_ADMIN_MESSAGES_ERROR'
export const GET_USER_MESSAGES_SUCCESS='GET_USER_MESSAGES_SUCCESS'
export const GET_USER_MESSAGES_ERROR='GET_USER_MESSAGES_ERROR'
export const MESSAGE_SEND_SUCCESS='MESSAGE_SEND_SUCCESS'
export const MESSAGE_SEND_ERROR='MESSAGE_SEND_ERROR'
export const ADMIN_REPLY_SUCCESS='ADMIN_REPLY_SUCCESS'
export const ADMIN_REPLY_ERROR='ADMIN_REPLY_ERROR'
export const CLEAR_ERROR='CLEAR_ERROR'
export const CLEAR_INFO='CLEAR_INFO'
export const LOGOUT ="LOGOUT"
export const FORGOT_PASSWORD_SUCCESS='FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR='FORGOT_PASSWORD_ERROR';

